apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ld0a25zxa-go
  janus-idp.io/tekton: ld0a25zxa-go
  backstage.io/kubernetes-id: ld0a25zxa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ld0a25zxa-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
