apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ld0a25zxa-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ld0a25zxa-go 
  name: ld0a25zxa-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ld0a25zxa-go 
